name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Generate GitHub stats
      run: |
        npx github-stats --output ./github-stats.svg
        npx github-langs --output ./github-langs.svg

    - name: Upload GitHub Stats
      uses: actions/upload-artifact@v3
      with:
        name: github-stats
        path: ./github-stats.svg

    - name: Upload GitHub Langs
      uses: actions/upload-artifact@v3
      with:
        name: github-langs
        path: ./github-langs.svg
