name: GitHub Stats Update

on:
  schedule:
    - cron: '0 * * * *' # Atualiza a cada hora, sempre no minuto 0
  workflow_dispatch: # Permite rodar manualmente

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Atualizar GitHub Stats
        run: |
          curl -o github-stats.svg "https://github-readme-stats.vercel.app/api?username=JorgeAugustoWilchen&show_icons=true&count_private=true&theme=dracula&token=${{ secrets.GH_STATS_TOKEN }}"
      
      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add github-stats.svg
          git commit -m "Atualizar GitHub Stats" || echo "Nenhuma mudança para commit"
          git push https://x-access-token:${{ secrets.GH_STATS_TOKEN }}@github.com/JorgeAugustoWilchen/JorgeAugustoWilchen.git
